mobile_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'
  publish_rate: 10.0               # default: 50
  # Assuming max travel distance of 10m
  # Assuming max deviation of 1 in / m = 0.0254 m / m
  pose_covariance_diagonal : [1.04e-5, 0.065, 1000.0, 1000.0, 1000.0, 1000.0]
  twist_covariance_diagonal: [0.0046, 3.7e-8, 1000.0, 1000.0, 1000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.153
  wheel_radius : 0.03

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.75

  # Base frame_id
  base_frame_id: base_link #default: base_link
  enable_odom_tf: false

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.075  # m/s
      min_velocity           : -0.075 # m/s
      has_acceleration_limits: true
      max_acceleration       : 2  # m/s^2 # rad/s #@TODO - Figure out the correct value
      min_acceleration       : -2 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 5.0  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.9804 # rad/s #@TODO - [(2*Vmax) / d] for skid steer and [Vmax / d] for diff steer.
      has_acceleration_limits: true
      max_acceleration       : 1.5  # rad/s^2 # rad/s #@TODO - Figure out the correct value
      has_jerk_limits        : true
      max_jerk               : 2.5  # rad/s^3
